### ISSUE TITLE
Custom key mappings for ctrl keys

### ISSUE THREAD

**Issue by Kache** [gregsexton/gitv#119]
Currently unable to set my own ctrl key mappings, what I'd like to do is:

```vim
" set J and K and disable <c-j>, <c-k>, and <c-l> (or change to something I don't use)
let g:Gitv_CustomMappings = {
  \'ctrlPreviousCommit': 'J',
  \'ctrlNextCommit': 'K',
  \'ctrlSplit': '',
  \'ctrlVsplit': '',
  \'ctrlTabe': ''
\}
```

Currently what I've done locally is

```vim
let g:Gitv_DoNotMapCtrlKey = 1
```
and:

```diff
diff --git a/plugin/gitv.vim b/plugin/gitv.vim
index 5470ba1..59ad2fe 100644
--- a/plugin/gitv.vim
+++ b/plugin/gitv.vim
@@ -1005,6 +1005,19 @@ fu! s:SetDefaultMappings() "{{{
             \'preventCustomBindings': 1,
             \'bindings': '<c-l>'
         \}
+    else
+        let s:defaultMappings.ctrlPreviousCommit = {
+            \'mapCmd': 'nmap',
+            \'cmd': '<Plug>(gitv-previous-commit)',
+            \'preventCustomBindings': 1,
+            \'bindings': 'J'
+        \}
+        let s:defaultMappings.ctrlNextCommit = {
+            \'mapCmd': 'nmap',
+            \'cmd': '<Plug>(gitv-next-commit)',
+            \'preventCustomBindings': 1,
+            \'bindings': 'K'
+        \}
     endif
 endf "}}}
 fu! s:NormalCmd(mapId, mappings) "{{{
```

Is there a particular reason `'preventCustomBindings': 1` is set on all the ctrl key maps? Playing with the script, the "what I'd like to do" above appears to work without `preventCustomBindings`.

**Comment by rbong** [comment]
Even though they use the same declarative syntax internally, ctrl bindings will not be exposed, as then a user could define bindings and then immediately disable them with the `b:Gitv_DoNotMapCtrlKey`, which could be confusing. Although I will admit that keeping this setting at all is confusing now that a more robust binding system is available, I'm not yet ready to remove it as it is convenient. I've now explained this in documentation to prevent future confusion.

Historically, previousCommit and nextCommit were not exposed because they're used internally.

I've made previousCommit and nextCommit bindable, and I've made `J` and `K` the defaults, as that makes it much easier to explain in documentation (and I'm guessing that users who still just need `b:Gitv_DoNotMapCtrlKey` need something to use).

You should find that the most recent commit works for you and that all the available bindings are now exposed.
