### ISSUE TITLE
Git stat for latest commit doesn't work

### ISSUE THREAD

**Issue by patpan001** [gregsexton/gitv#127]
using S to get stat for latest commit doesn't work. It works fine for other commits.
Test case:
Open file of git repository
Issue :Gitv
get cursor on first line on repo browser
hit S
It doesn't open stats for that commit.

**Comment by rbong** [comment]
S in normal mode opens a diffstat to see the differences from that commit and the current head, so using S on the current head results in no differences. If you'd like to see a summary of differences, you can press `<CR>`.

However S in visual mode was broken, so that's been fixed.

Feel free to reopen if that doesn't address your issue, I am only closing this because it's old and I don't expect you to be able to respond right away.
