### ISSUE TITLE
Provide a keystroke for editing a file from a commit in history

### ISSUE THREAD

**Issue by dkvasnicka** [gregsexton/gitv#129]
Quite often I find myself in a situation where I want to fire up the history of the repo and open a file that was recently edited in a commit. Would it be possible to introduce a key binding (or hook into `:Gedit` somehow) that would allow me to open a commit, go to the appropriate line in the file list and open the local copy for editing?
I searched the docs and tried a few things but no luck.
https://github.com/jonas/tig can do it pretty nicely but I'd love to be able to do this without leaving Vim.

**Comment by rbong** [comment]
@dkvasnicka actually, this is built into fugitive, so you can do this in Gitv too.

Simply view the file you wish to open in the commit viewer, make sure your cursor is over either a `+` or `-` line (so fugitive knows which revision to go to), and press the enter key.

Please feel free to reopen this issue if this does not solve your problem, I am closing this because it took me so long to get around to this issue and I do not anticipate that you will be watching it closely. Apologies, I have reworked my schedule and I should now have more time to work on Gitv.

**Comment by dkvasnicka** [comment]
Thanks for the hint! This works, kind of... pressing enter opens a revision but not the local copy, which is what I wanted to do. However, that can be fixed by doing `ge`.

**Comment by rbong** [comment]
That's correct, missed that step.
