### ISSUE TITLE
merging-to-current enhancement

### ISSUE THREAD

**Issue by phmarek** [gregsexton/gitv#31]
I've got a remote branch that I want to merge (1 commit, ff possible).

After choosing the two lines and pressing 'm' I get asked 3 questions.
This is especially bothersome if one of the points has a few branches defined on it - then I have to read the list at the bottom, find the one I want, and get the correct ID; in about 10 tests I've err'ed at least 3 times (mixed start and end point, choose wrong branch).

How about optimizing for the trivial case (merging onto the current branch), and allow some hotkey to try a merge without asking that much?
Sadly both "M" and "m" are used for normal mode, although I think "m" could be reused -- or at least switch to that if only part of a single line is marked visually.

Ie. I'm standing on a (syntax colored) branchname "remote/branch" - pressing "m" (or, alternatively, visually marking that branch name and then pressing "m")  should just call "git merge <selection>" and be done.

Thanks a lot,

Phil

**Comment by rbong** [comment]
@phmarek you should just be able to use `cp` right now if you're just cherry picking.

I'm not sure that merge works for everyone's use case right now. There may be users like @phmarek who always wish to fast-forward. There may be users like @gregsexton who wish to customize fast-forward. And what of merging with different strategies?

I'm not comfortable adding a bunch of different bindings for different merge use cases given that the bindings just blew up with bisect and rebase added. What happens when we start getting into adding more arguments for that? I think that just an option that says "do not ask me for --no-ff" is not enough.

I also don't want to break existing functionality.

Therefore, I am adding an option, `g:Gitv_MergeArgs`. If users wish to disable the default behaviour, they can set it to an empty string. If they want to use the default behaviour, they can simply not define it. If they wish to do different strategies they can. The only downside is if they wish to use some combination of the default behaviour and the MergeArgs behaviour, they must define it themselves. More information has been added to the documentation.
