### ISSUE TITLE
can't run gitv from the shell prompt

### ISSUE THREAD

**Issue by bart9h** [gregsexton/gitv#65]
When I run `vim -c Gitv` (from inside a directory with a `.git/`, of course), it gives an error `Not a git repository.`

If I run `vim`, then `:Gitv<CR>`, it works.

(I'd like to `alias gitv='vim -c Gitv'` to run it directly from the bash prompt, maybe as a substitute to `tig`.)

**Comment by luisdavim** [comment]
That alias does not work for me. I only get garbled text.
But if I run ```vim```, then ```:Gitv<CR>```, it works.

**Comment by rbong** [comment]
@luisdavim I cannot reproduce, I suspect this may have had to do with some semi-recent fixes. I'm closing this out for now since I suspect it's been too long for you to be keeping an eye on the issue.

If anyone has the same issue as @luisdavim above, please make sure you are on the latest version. Please post your terminal emulator and `vim --version` as I suspect that may also have some impact, and please post a repository if you can.
