### ISSUE TITLE
Some way to set what to show on screen to always see author and date

### ISSUE THREAD

**Issue by wolftune** [gregsexton/gitv#94]
I really want to see author and date on screen, but if I have a commit that matches several remotes, then the listing of the remotes pushes *all* the lines to be so long that author and date for everything is off-screen. Is there some way to wrap/truncate/handle this so that I can see everything, like I do in gitk?

**Comment by aisapatino** [comment]
@wolftune If you're still looking for this, you could try `let g:Gitv_TruncateCommitSubjects = 1`.

If your screen is super narrow, it might be worse because it'll shorten the commit messages while leaving everything else at full length. But on a medium-sized screen it might be helpful.

On a 15" laptop, with an unusually long committer name:

<img width="713" alt="screen shot 2015-12-08 at 3 37 00 pm" src="https://cloud.githubusercontent.com/assets/1279315/11672026/99881870-9dc1-11e5-8fe1-598cf1962748.png">

Alternatively, there is an option to wrap lines: `g:Gitv_WrapLines`. But the alignment is totally disrupted and it ends up looking worse imo.

**Comment by wolftune** [comment]
Thanks that helps! Good enough for me for now.
